function JacType(IDdict::Dict{Symbol,StepRangeLen{Int,Int,Int,Int}})
    Ngrid = length(first(IDdict)[2])
    nspec = length(IDdict)
    @unpack POCID, FeOOHID, FeSID, SO4ID, TFeID, HID, TCO2ID, TH2SID, LorgID =
        IDdict

    rowID = Vector{Int}()
    colID = Vector{Int}()
    append!(rowID, getindex(POCID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(POCID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(POCID, 1:Ngrid))
    append!(colID, getindex(FeOOHID, 1:Ngrid))
    append!(rowID, getindex(POCID, 1:Ngrid))
    append!(colID, getindex(POCID, 1:Ngrid))
    append!(rowID, getindex(POCID, 1:Ngrid))
    append!(colID, getindex(SO4ID, 1:Ngrid))
    append!(rowID, getindex(FeOOHID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(FeOOHID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(FeOOHID, 1:Ngrid))
    append!(colID, getindex(FeOOHID, 1:Ngrid))
    append!(rowID, getindex(FeOOHID, 1:Ngrid))
    append!(colID, getindex(POCID, 1:Ngrid))
    append!(rowID, getindex(FeOOHID, 1:Ngrid))
    append!(colID, getindex(TH2SID, 1:Ngrid))
    append!(rowID, getindex(FeSID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(FeSID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(FeSID, 1:Ngrid))
    append!(colID, getindex(TCO2ID, 1:Ngrid))
    append!(rowID, getindex(FeSID, 1:Ngrid))
    append!(colID, getindex(HID, 1:Ngrid))
    append!(rowID, getindex(FeSID, 1:Ngrid))
    append!(colID, getindex(TH2SID, 1:Ngrid))
    append!(rowID, getindex(FeSID, 1:Ngrid))
    append!(colID, getindex(TFeID, 1:Ngrid))
    append!(rowID, getindex(FeSID, 1:Ngrid))
    append!(colID, getindex(POCID, 1:Ngrid))
    append!(rowID, getindex(FeSID, 1:Ngrid))
    append!(colID, getindex(Lorg_disID, 1:Ngrid))
    append!(rowID, getindex(FeSID, 1:Ngrid))
    append!(colID, getindex(Fe_aqID, 1:Ngrid))
    append!(rowID, getindex(FeSID, 1:Ngrid))
    append!(colID, getindex(SO4ID, 1:Ngrid))
    append!(rowID, getindex(FeSID, 1:Ngrid))
    append!(colID, getindex(LorgID, 1:Ngrid))
    append!(rowID, getindex(SO4ID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(SO4ID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(SO4ID, 1:Ngrid))
    append!(colID, getindex(SO4ID, 1:Ngrid))
    append!(rowID, getindex(SO4ID, 1:Ngrid))
    append!(colID, getindex(FeOOHID, 1:Ngrid))
    append!(rowID, getindex(SO4ID, 1:Ngrid))
    append!(colID, getindex(POCID, 1:Ngrid))
    append!(rowID, getindex(TFeID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(TFeID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(TFeID, 1:Ngrid))
    append!(colID, getindex(FeOOHID, 1:Ngrid))
    append!(rowID, getindex(TFeID, 1:Ngrid))
    append!(colID, getindex(POCID, 1:Ngrid))
    append!(rowID, getindex(TFeID, 1:Ngrid))
    append!(colID, getindex(TH2SID, 1:Ngrid))
    append!(rowID, getindex(TFeID, 1:Ngrid))
    append!(colID, getindex(TCO2ID, 1:Ngrid))
    append!(rowID, getindex(TFeID, 1:Ngrid))
    append!(colID, getindex(HID, 1:Ngrid))
    append!(rowID, getindex(TFeID, 1:Ngrid))
    append!(colID, getindex(TFeID, 1:Ngrid))
    append!(rowID, getindex(TFeID, 1:Ngrid))
    append!(colID, getindex(Lorg_disID, 1:Ngrid))
    append!(rowID, getindex(TFeID, 1:Ngrid))
    append!(colID, getindex(Fe_aqID, 1:Ngrid))
    append!(rowID, getindex(TFeID, 1:Ngrid))
    append!(colID, getindex(SO4ID, 1:Ngrid))
    append!(rowID, getindex(TFeID, 1:Ngrid))
    append!(colID, getindex(LorgID, 1:Ngrid))
    append!(rowID, getindex(TFeID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(POCID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(HID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(HID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(HID, 1:Ngrid))
    append!(colID, getindex(FeOOHID, 1:Ngrid))
    append!(rowID, getindex(HID, 1:Ngrid))
    append!(colID, getindex(POCID, 1:Ngrid))
    append!(rowID, getindex(HID, 1:Ngrid))
    append!(colID, getindex(SO4ID, 1:Ngrid))
    append!(rowID, getindex(HID, 1:Ngrid))
    append!(colID, getindex(TH2SID, 1:Ngrid))
    append!(rowID, getindex(HID, 1:Ngrid))
    append!(colID, getindex(TCO2ID, 1:Ngrid))
    append!(rowID, getindex(HID, 1:Ngrid))
    append!(colID, getindex(HID, 1:Ngrid))
    append!(rowID, getindex(HID, 1:Ngrid))
    append!(colID, getindex(TFeID, 1:Ngrid))
    append!(rowID, getindex(HID, 1:Ngrid))
    append!(colID, getindex(Lorg_disID, 1:Ngrid))
    append!(rowID, getindex(HID, 1:Ngrid))
    append!(colID, getindex(Fe_aqID, 1:Ngrid))
    append!(rowID, getindex(HID, 1:Ngrid))
    append!(colID, getindex(LorgID, 1:Ngrid))
    append!(rowID, getindex(TCO2ID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(TCO2ID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(TCO2ID, 1:Ngrid))
    append!(colID, getindex(FeOOHID, 1:Ngrid))
    append!(rowID, getindex(TCO2ID, 1:Ngrid))
    append!(colID, getindex(POCID, 1:Ngrid))
    append!(rowID, getindex(TCO2ID, 1:Ngrid))
    append!(colID, getindex(SO4ID, 1:Ngrid))
    append!(rowID, getindex(TCO2ID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(HID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(TH2SID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(TH2SID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(TH2SID, 1:Ngrid))
    append!(colID, getindex(SO4ID, 1:Ngrid))
    append!(rowID, getindex(TH2SID, 1:Ngrid))
    append!(colID, getindex(FeOOHID, 1:Ngrid))
    append!(rowID, getindex(TH2SID, 1:Ngrid))
    append!(colID, getindex(POCID, 1:Ngrid))
    append!(rowID, getindex(TH2SID, 1:Ngrid))
    append!(colID, getindex(TH2SID, 1:Ngrid))
    append!(rowID, getindex(TH2SID, 1:Ngrid))
    append!(colID, getindex(TCO2ID, 1:Ngrid))
    append!(rowID, getindex(TH2SID, 1:Ngrid))
    append!(colID, getindex(HID, 1:Ngrid))
    append!(rowID, getindex(TH2SID, 1:Ngrid))
    append!(colID, getindex(TFeID, 1:Ngrid))
    append!(rowID, getindex(TH2SID, 1:Ngrid))
    append!(colID, getindex(Lorg_disID, 1:Ngrid))
    append!(rowID, getindex(TH2SID, 1:Ngrid))
    append!(colID, getindex(Fe_aqID, 1:Ngrid))
    append!(rowID, getindex(TH2SID, 1:Ngrid))
    append!(colID, getindex(LorgID, 1:Ngrid))
    append!(rowID, getindex(TH2SID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(HID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(LorgID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(LorgID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(HID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(TCO2ID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    append!(rowID, getindex(HID, vcat(1:Ngrid, 1:(Ngrid-1), 2:Ngrid)))
    append!(colID, getindex(TH2SID, vcat(1:Ngrid, 2:Ngrid, 1:(Ngrid-1))))
    return sparse(
        rowID,
        colID,
        ones(length(rowID)),
        Ngrid * nspec,
        Ngrid * nspec,
    )
end
