name: CI
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}  - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    env:
      GR_BACKEND: ${{ matrix.os == 'windows-latest' && 'Null' || 'default' }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.11', '1.8']
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: actions/cache@v5
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - if: matrix.os == 'ubuntu-latest'
        run: > 
          sudo apt-get install --no-install-recommends gfortran python3-setuptools python3-wheel
          && pip3 install sympy
      - name: Repair / prebuild GR on Windows
        if: matrix.os == 'windows-latest'
        run: |
          julia -e 'using Pkg; Pkg.instantiate(); try
            import GR
            try
              GR.GRPreferences.use_jll_binary()
            catch
              GR.GRPreferences.use_upstream_binary()
            end
          catch err
            @warn "GR import/repair attempt failed, building GR" err
            Pkg.build("GR")
          end'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
